title: WNL Gamers
description: Board games in Wootton, Bedford
author: WNL Gamers
baseurl: "/website" # leave this empty for a project site
url: "https://wnlgamers.uk" 
# You can override colours in your custom CSS below
# theme: midnight
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  pages:
    output: true
    permalink: /:path/

