title: WNL Gamers
description: Board games in Wootton, Bedford â€“ your community hub for fun and connection.
author: WNL Gamers
baseurl: "" # leave this empty for a project site
url: "https://wnlgamers.github.io/website" 
# You can override colours in your custom CSS below
# theme: midnight
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

